DROP TABLE IF EXISTS LIVECAST_IP_DICT;

CREATE TABLE LIVECAST_IP_DICT (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(500) NOT NULL,
	NAME_DETAIL VARCHAR(2000),
	SERVER_IP VARCHAR(1000) NOT NULL,
    CLIENT_IP_RANGE VARCHAR(5000) NOT NULL,
    CREATE_TIME TIMESTAMP  NOT NULL,
    UPDATE_TIME TIMESTAMP  NOT NULL,   
    PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS LIVECAST_CONF;

CREATE TABLE LIVECAST_CONF (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(500) NOT NULL,
	VALUE VARCHAR(2000),	
    CREATE_TIME TIMESTAMP  NOT NULL,
    UPDATE_TIME TIMESTAMP  NOT NULL,   
    PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS LIVECAST_ROOM;

CREATE TABLE LIVECAST_ROOM (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(500) NOT NULL,
	ROOM_DETAIL VARCHAR(2000),
    ROOM_PASSWORD VARCHAR(500),
    MEDIA_KEY VARCHAR(500),
    RTMP_URL VARCHAR(500),
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    CREATE_TIME TIMESTAMP  NOT NULL,
    UPDATE_TIME TIMESTAMP  NOT NULL,
    VERSION BIGINT NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS LIVECAST_ROOM_AUTH;

CREATE TABLE LIVECAST_ROOM_AUTH (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	ROOM_ID BIGINT NOT NULL,
	AUTH_URL VARCHAR(1000), 
    CREATE_TIME TIMESTAMP  NOT NULL,
    UPDATE_TIME TIMESTAMP  NOT NULL,
    CREATE_BY BIGINT,
    UPDATE_BY BIGINT,
    VERSION BIGINT NOT NULL,
    PRIMARY KEY (ID),
    KEY ROOM_ID (ROOM_ID),
  CONSTRAINT LIVECAST_ROOM_AUTH_ibfk_1 FOREIGN KEY (ROOM_ID) REFERENCES LIVECAST_ROOM (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS LIVECAST_ROOM_CONSOLE;

CREATE TABLE LIVECAST_ROOM_CONSOLE (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	ROOM_ID BIGINT NOT NULL,
	NUMBER_LIMIT BIGINT,
    P2P_ENABLE INTEGER,
    CREATE_TIME TIMESTAMP  NOT NULL,
    UPDATE_TIME TIMESTAMP  NOT NULL,
    CREATE_BY BIGINT,
    UPDATE_BY BIGINT,
    VERSION BIGINT NOT NULL,
    PRIMARY KEY (ID),
    KEY ROOM_ID (ROOM_ID),
  CONSTRAINT LIVECAST_ROOM_CONSOLE_ibfk_1 FOREIGN KEY (ROOM_ID) REFERENCES LIVECAST_ROOM (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;